import AppKit
import ClipboardCore
import Logging

class Clipboard: @unchecked Sendable {
  static let shared = Clipboard()

  typealias OnNewCoreCopyHook = (ClipboardStoredItem) -> Void

  private var onNewCoreCopyHooks: [OnNewCoreCopyHook] = []
  var changeCount: Int

  private let pasteboard = NSPasteboard.general
  private let performancePolicy = ClipboardRuntimePerformancePolicy.default

  private var timer: Timer?
  private let logger = Logger(label: "com.local.MaccyLite.clipboard")
  private let captureQueue = DispatchQueue(label: "com.local.MaccyLite.clipboard.capture", qos: .utility)
  private var cachedIgnoreRegexpPatterns: [String] = []
  private var cachedIgnoreRegexps: [NSRegularExpression] = []

  private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
    .fileURL,
    .html,
    .heic,
    .jpeg,
    .png,
    .rtf,
    .string,
    .tiff
  ]
  private let readPriority: [NSPasteboard.PasteboardType] = [
    .string,
    .fileURL,
    .html,
    .rtf,
    .png,
    .tiff,
    .jpeg,
    .heic
  ]
  private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
    .autoGenerated,
    .concealed,
    .transient
  ]

  private var enabledTypes: Set<NSPasteboard.PasteboardType> { AppPreferences.enabledPasteboardTypes }
  private var captureRules: ClipboardPasteboardCaptureRules {
    ClipboardPasteboardCaptureRules(
      supportedTypes: Set(supportedTypes.map(\.rawValue)),
      enabledTypes: Set(enabledTypes.map(\.rawValue)),
      ignoredTypes: Set(ignoredTypes.map(\.rawValue))
        .union(AppPreferences.ignoredPasteboardTypes)
    )
  }

  private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

  init() {
    changeCount = pasteboard.changeCount
  }

  func onNewCoreCopy(_ hook: @escaping OnNewCoreCopyHook) {
    onNewCoreCopyHooks.append(hook)
  }

  func start() {
    timer = Timer.scheduledTimer(
      timeInterval: AppPreferences.clipboardCheckInterval,
      target: self,
      selector: #selector(checkForChangesInPasteboard),
      userInfo: nil,
      repeats: true
    )
  }

  func restart() {
    timer?.invalidate()
    start()
  }

  @MainActor
  func copy(_ string: String) {
    pasteboard.clearContents()
    pasteboard.setString(string, forType: .string)
    sync()
    checkForChangesInPasteboard()
  }

  @MainActor
  func copy(contents: [(type: String, data: Data)], sourceApp: String?) {
    pasteboard.clearContents()
    for content in contents where content.type != NSPasteboard.PasteboardType.fileURL.rawValue {
      pasteboard.setData(content.data, forType: NSPasteboard.PasteboardType(content.type))
    }

    let fileURLObjects: [NSURL] = contents.compactMap { content in
      guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
      guard let string = String(data: content.data, encoding: .utf8),
            let url = URL(string: string),
            url.isFileURL else {
        return nil
      }
      return url as NSURL
    }

    if !fileURLObjects.isEmpty {
      pasteboard.writeObjects(fileURLObjects)
    } else {
      let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
        guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
        let pasteItem = NSPasteboardItem()
        pasteItem.setData(content.data, forType: NSPasteboard.PasteboardType(content.type))
        return pasteItem
      }
      pasteboard.writeObjects(fileURLItems)
    }

    pasteboard.setString("", forType: .fromMaccy)
    pasteboard.setString(sourceApp ?? "", forType: .source)
    sync()

    Task {
      checkForChangesInPasteboard()
    }
  }

  @discardableResult
  func paste() -> Bool {
    PasteController.shared.paste()
  }

  func clear() {
    guard AppPreferences.clearSystemClipboard else {
      return
    }

    pasteboard.clearContents()
  }

  @objc
  @MainActor
  func checkForChangesInPasteboard() { // swiftlint:disable:this cyclomatic_complexity
    let captureStartedAt = ContinuousClock.now

    guard pasteboard.changeCount != changeCount else {
      return
    }

    changeCount = pasteboard.changeCount

    if AppPreferences.ignoreEvents {
      if AppPreferences.ignoreOnlyNextEvent {
        AppPreferences.ignoreEvents = false
        AppPreferences.ignoreOnlyNextEvent = false
      }

      return
    }

    // Reading types on NSPasteboard gives all the available
    // types - even the ones that are not present on the NSPasteboardItem.
    // See https://github.com/p0deje/Maccy/issues/241.
    let captureRules = captureRules
    let pasteboardTypes = Set((pasteboard.types ?? []).map(\.rawValue))
    if captureRules.shouldIgnorePasteboard(types: pasteboardTypes) {
      return
    }

    let sourceAppBundle = sourceApp?.bundleIdentifier
    if let sourceAppBundle, shouldIgnore(sourceAppBundle) {
      return
    }

    // Some applications (BBEdit, Edge) add 2 items to pasteboard when copying
    // so it's better to merge all data into a single record.
    // - https://github.com/p0deje/Maccy/issues/78
    // - https://github.com/p0deje/Maccy/issues/472
    var coreContents = [ClipboardRawContent]()
    let regexps = ignoreRegexps()
    let copiedAt = Date.now
    pasteboard.pasteboardItems?.forEach({ item in
      let itemTypes = Set(item.types)
      let hasRichTextPayload = hasRichTextPayload(itemTypes)
      let needsPlainText = !regexps.isEmpty || (itemTypes.contains(.string) && !hasRichTextPayload)
      let plainText = needsPlainText ? item.string(forType: .string) : nil

      if shouldIgnore(plainText: plainText, regexps: regexps) {
        return
      }

      let types = captureRules.selectedItemTypes(
        from: Set(itemTypes.map(\.rawValue)),
        hasEmptyPlainText: itemTypes.contains(.string) && !hasRichTextPayload && isEmptyString(plainText),
        hasRichTextPayload: hasRichTextPayload
      )

      orderedTypes(types).forEach { type in
        let data = item.data(forType: NSPasteboard.PasteboardType(type))
        if let data {
          coreContents.append(ClipboardRawContent(pasteboardType: type, data: data))
        }
      }
    })

    guard !coreContents.isEmpty else {
      return
    }

    let pasteboardReadAt = ContinuousClock.now
    let logger = logger

    captureQueue.async { [weak self] in
      let coreItem = ClipboardCoreStore.shared.insert(
        contents: coreContents,
        sourceApp: sourceAppBundle,
        copiedAt: copiedAt
      )
      let insertedAt = ContinuousClock.now

      let captureSample = ClipboardCapturePerformanceSample(
        typeCount: coreContents.count,
        readMilliseconds: captureStartedAt.duration(to: pasteboardReadAt).milliseconds,
        insertMilliseconds: pasteboardReadAt.duration(to: insertedAt).milliseconds,
        totalMilliseconds: captureStartedAt.duration(to: insertedAt).milliseconds
      )
      let captureMessage = "Clipboard capture sample: types=\(captureSample.typeCount) read_ms=\(captureSample.readMilliseconds) insert_ms=\(captureSample.insertMilliseconds) total_ms=\(captureSample.totalMilliseconds)"
      if self?.performancePolicy.captureExceededWarningThreshold(captureSample) == true {
        logger.warning("\(captureMessage)")
      } else {
        logger.debug("\(captureMessage)")
      }

      guard let coreItem else {
        return
      }

      DispatchQueue.main.async {
        self?.onNewCoreCopyHooks.forEach({ $0(coreItem) })
      }
    }
  }

  private func shouldIgnore(_ sourceAppBundle: String) -> Bool {
    if AppPreferences.ignoreAllAppsExceptListed {
      return !AppPreferences.ignoredApps.contains(sourceAppBundle)
    } else {
      return AppPreferences.ignoredApps.contains(sourceAppBundle)
    }
  }

  private func shouldIgnore(plainText string: String?, regexps: [NSRegularExpression]) -> Bool {
    guard !regexps.isEmpty, let string else {
      return false
    }

    let range = NSRange(string.startIndex..., in: string)
    for regex in regexps {
      if regex.numberOfMatches(in: string, range: range) > 0 {
        return true
      }
    }
    return false
  }

  private func ignoreRegexps() -> [NSRegularExpression] {
    let patterns = AppPreferences.ignoreRegexp
    guard patterns != cachedIgnoreRegexpPatterns else {
      return cachedIgnoreRegexps
    }

    cachedIgnoreRegexpPatterns = patterns
    cachedIgnoreRegexps = patterns.compactMap { try? NSRegularExpression(pattern: $0) }
    return cachedIgnoreRegexps
  }

  private func orderedTypes(_ types: Set<String>) -> [String] {
    let known = readPriority
      .map(\.rawValue)
      .filter(types.contains)
    let knownSet = Set(known)
    return known + types.subtracting(knownSet).sorted()
  }

  private func isEmptyString(_ string: String?) -> Bool {
    guard let string else {
      return true
    }

    return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
  }

  private func hasRichTextPayload(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
    return types.contains(.rtf) || types.contains(.html)
  }

  // Some applications requires window be unfocused and focused back to sync the clipboard.
  // - Chrome Remote Desktop (https://github.com/p0deje/Maccy/issues/948)
  // - Netbeans (https://github.com/p0deje/Maccy/issues/879)
  private func sync() {
    guard let app = sourceApp,
          app.bundleURL?.lastPathComponent == "Chrome Remote Desktop.app" ||
            app.localizedName?.contains("NetBeans") == true else {
      return
    }

    NSApp.activate(ignoringOtherApps: true)
    NSApp.hide(self)
  }

}

private extension Duration {
  var milliseconds: Double {
    Double(components.seconds) * 1000 + Double(components.attoseconds) / 1_000_000_000_000_000
  }
}
