import AppKit
import ClipboardCore
import Defaults
import Logging

class Clipboard: @unchecked Sendable {
  static let shared = Clipboard()

  typealias OnNewCoreCopyHook = (ClipboardStoredItem) -> Void

  private var onNewCoreCopyHooks: [OnNewCoreCopyHook] = []
  var changeCount: Int

  private let pasteboard = NSPasteboard.general

  private var timer: Timer?
  private let logger = Logger(label: "com.local.MaccyLite.clipboard")
  private let captureQueue = DispatchQueue(label: "com.local.MaccyLite.clipboard.capture", qos: .utility)

  private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
    .fileURL,
    .html,
    .png,
    .rtf,
    .string,
    .tiff
  ]
  private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
    .autoGenerated,
    .concealed,
    .transient
  ]

  private var enabledTypes: Set<NSPasteboard.PasteboardType> { Defaults[.enabledPasteboardTypes] }
  private var captureRules: ClipboardPasteboardCaptureRules {
    ClipboardPasteboardCaptureRules(
      supportedTypes: Set(supportedTypes.map(\.rawValue)),
      enabledTypes: Set(enabledTypes.map(\.rawValue)),
      ignoredTypes: Set(ignoredTypes.map(\.rawValue))
        .union(Defaults[.ignoredPasteboardTypes])
    )
  }

  private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

  init() {
    changeCount = pasteboard.changeCount
  }

  func onNewCoreCopy(_ hook: @escaping OnNewCoreCopyHook) {
    onNewCoreCopyHooks.append(hook)
  }

  func start() {
    timer = Timer.scheduledTimer(
      timeInterval: Defaults[.clipboardCheckInterval],
      target: self,
      selector: #selector(checkForChangesInPasteboard),
      userInfo: nil,
      repeats: true
    )
  }

  func restart() {
    timer?.invalidate()
    start()
  }

  @MainActor
  func copy(_ string: String) {
    pasteboard.clearContents()
    pasteboard.setString(string, forType: .string)
    sync()
    checkForChangesInPasteboard()
  }

  @MainActor
  func copy(contents: [(type: String, data: Data)], sourceApp: String?) {
    pasteboard.clearContents()
    for content in contents where content.type != NSPasteboard.PasteboardType.fileURL.rawValue {
      pasteboard.setData(content.data, forType: NSPasteboard.PasteboardType(content.type))
    }

    let fileURLObjects: [NSURL] = contents.compactMap { content in
      guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
      guard let string = String(data: content.data, encoding: .utf8),
            let url = URL(string: string),
            url.isFileURL else {
        return nil
      }
      return url as NSURL
    }

    if !fileURLObjects.isEmpty {
      pasteboard.writeObjects(fileURLObjects)
    } else {
      let fileURLItems: [NSPasteboardItem] = contents.compactMap { content in
        guard content.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
        let pasteItem = NSPasteboardItem()
        pasteItem.setData(content.data, forType: NSPasteboard.PasteboardType(content.type))
        return pasteItem
      }
      pasteboard.writeObjects(fileURLItems)
    }

    pasteboard.setString("", forType: .fromMaccy)
    pasteboard.setString(sourceApp ?? "", forType: .source)
    sync()

    Task {
      checkForChangesInPasteboard()
    }
  }

  @discardableResult
  func paste() -> Bool {
    PasteController.shared.paste()
  }

  func clear() {
    guard Defaults[.clearSystemClipboard] else {
      return
    }

    pasteboard.clearContents()
  }

  @objc
  @MainActor
  func checkForChangesInPasteboard() { // swiftlint:disable:this cyclomatic_complexity
    let captureStartedAt = ContinuousClock.now

    guard pasteboard.changeCount != changeCount else {
      return
    }

    changeCount = pasteboard.changeCount

    if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromMaccy) }) != true {
      // External copy occurred. Stop the current paste stack.
      // Maybe queue it into the paste stack? Configurable behaviour?
      AppState.shared.history.interruptPasteStack()
    }

    if Defaults[.ignoreEvents] {
      if Defaults[.ignoreOnlyNextEvent] {
        Defaults[.ignoreEvents] = false
        Defaults[.ignoreOnlyNextEvent] = false
      }

      return
    }

    // Reading types on NSPasteboard gives all the available
    // types - even the ones that are not present on the NSPasteboardItem.
    // See https://github.com/p0deje/Maccy/issues/241.
    let captureRules = captureRules
    if captureRules.shouldIgnorePasteboard(types: Set((pasteboard.types ?? []).map(\.rawValue))) {
      return
    }

    if let sourceAppBundle = sourceApp?.bundleIdentifier, shouldIgnore(sourceAppBundle) {
      return
    }

    // Some applications (BBEdit, Edge) add 2 items to pasteboard when copying
    // so it's better to merge all data into a single record.
    // - https://github.com/p0deje/Maccy/issues/78
    // - https://github.com/p0deje/Maccy/issues/472
    var coreContents = [ClipboardRawContent]()
    let copiedAt = Date.now
    pasteboard.pasteboardItems?.forEach({ item in
      let itemTypes = Set(item.types)

      if shouldIgnore(item) {
        return
      }

      let types = captureRules.selectedItemTypes(
        from: Set(itemTypes.map(\.rawValue)),
        hasEmptyPlainText: itemTypes.contains(.string) && isEmptyString(item),
        hasRichTextPayload: hasRichTextPayload(item)
      )

      types.forEach { type in
        let data = item.data(forType: NSPasteboard.PasteboardType(type))
        if let data {
          coreContents.append(ClipboardRawContent(pasteboardType: type, data: data))
        }
      }
    })

    guard !coreContents.isEmpty else {
      return
    }

    let pasteboardReadAt = ContinuousClock.now
    let sourceAppBundle = sourceApp?.bundleIdentifier
    let logger = logger

    captureQueue.async { [weak self] in
      let coreItem = ClipboardCoreStore.shared.insert(
        contents: coreContents,
        sourceApp: sourceAppBundle,
        copiedAt: copiedAt
      )
      let insertedAt = ContinuousClock.now

      logger.debug(
        "Clipboard capture sample: types=\(coreContents.count) read_ms=\(captureStartedAt.duration(to: pasteboardReadAt).milliseconds) insert_ms=\(pasteboardReadAt.duration(to: insertedAt).milliseconds) total_ms=\(captureStartedAt.duration(to: insertedAt).milliseconds)"
      )

      guard let coreItem else {
        return
      }

      DispatchQueue.main.async {
        self?.onNewCoreCopyHooks.forEach({ $0(coreItem) })
      }

      if coreItem.contents.contains(where: { $0.imageWidth != nil || $0.imageHeight != nil }) {
        let thumbnailStartedAt = ContinuousClock.now
        let generated = ClipboardCoreStore.shared.generatePendingThumbnails()
        let elapsed = thumbnailStartedAt.duration(to: ContinuousClock.now).milliseconds
        if generated > 0 {
          logger.debug("Thumbnail generation sample: generated=\(generated) elapsed_ms=\(elapsed)")
        }
      }
    }
  }

  private func shouldIgnore(_ sourceAppBundle: String) -> Bool {
    if Defaults[.ignoreAllAppsExceptListed] {
      return !Defaults[.ignoredApps].contains(sourceAppBundle)
    } else {
      return Defaults[.ignoredApps].contains(sourceAppBundle)
    }
  }

  private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
    for regexp in Defaults[.ignoreRegexp] {
      if let string = item.string(forType: .string) {
        do {
          let regex = try NSRegularExpression(pattern: regexp)
          if regex.numberOfMatches(in: string, range: NSRange(string.startIndex..., in: string)) > 0 {
            return true
          }
        } catch {
          return false
        }
      }
    }
    return false
  }

  private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
    guard let string = item.string(forType: .string) else {
      return true
    }

    return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
  }

  private func hasRichTextPayload(_ item: NSPasteboardItem) -> Bool {
    item.data(forType: .rtf)?.isEmpty == false ||
      item.data(forType: .html)?.isEmpty == false
  }

  // Some applications requires window be unfocused and focused back to sync the clipboard.
  // - Chrome Remote Desktop (https://github.com/p0deje/Maccy/issues/948)
  // - Netbeans (https://github.com/p0deje/Maccy/issues/879)
  private func sync() {
    guard let app = sourceApp,
          app.bundleURL?.lastPathComponent == "Chrome Remote Desktop.app" ||
            app.localizedName?.contains("NetBeans") == true else {
      return
    }

    NSApp.activate(ignoringOtherApps: true)
    NSApp.hide(self)
  }

}

private extension Duration {
  var milliseconds: Double {
    Double(components.seconds) * 1000 + Double(components.attoseconds) / 1_000_000_000_000_000
  }
}
