import Foundation

public struct ClipboardPasteboardCaptureRules: Sendable, Equatable {
  public var supportedTypes: Set<String>
  public var enabledTypes: Set<String>
  public var ignoredTypes: Set<String>

  public init(
    supportedTypes: Set<String> = ClipboardPasteboardCaptureRules.defaultSupportedTypes,
    enabledTypes: Set<String> = ClipboardPasteboardCaptureRules.defaultSupportedTypes,
    ignoredTypes: Set<String> = ClipboardPasteboardCaptureRules.defaultIgnoredTypes
  ) {
    self.supportedTypes = supportedTypes
    self.enabledTypes = enabledTypes
    self.ignoredTypes = ignoredTypes
  }

  public func shouldIgnorePasteboard(types: Set<String>) -> Bool {
    types.isDisjoint(with: enabledTypes) || !types.isDisjoint(with: ignoredTypes)
  }

  public func selectedItemTypes(
    from types: Set<String>,
    hasEmptyPlainText: Bool,
    hasRichTextPayload: Bool
  ) -> Set<String> {
    if types.contains(ClipboardContentType.plainText),
       hasEmptyPlainText,
       !hasRichTextPayload {
      return []
    }

    let disabledTypes = supportedTypes.subtracting(enabledTypes)
    var selected = types
      .subtracting(disabledTypes)
      .filter { !$0.starts(with: Self.dynamicTypePrefix) }
      .filter { !$0.starts(with: Self.microsoftSourcePrefix) }

    if selected.isSuperset(of: [Self.microsoftLinkSource, Self.microsoftObjectLink]) {
      selected.subtract([Self.microsoftLinkSource, Self.microsoftObjectLink, Self.pdf])
    }

    return selected
  }

  public static let defaultSupportedTypes: Set<String> = [
    ClipboardContentType.fileURL,
    ClipboardContentType.html,
    ClipboardContentType.plainText,
    ClipboardContentType.png,
    ClipboardContentType.rtf,
    ClipboardContentType.tiff
  ]

  public static let defaultIgnoredTypes: Set<String> = [
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType"
  ]

  public static let dynamicTypePrefix = "dyn."
  public static let microsoftSourcePrefix = "com.microsoft.ole.source."
  public static let microsoftObjectLink = "com.microsoft.ObjectLink"
  public static let microsoftLinkSource = "com.microsoft.Link-Source"
  public static let pdf = "com.adobe.pdf"
}
